// Generated by jextract

package org.apache.lucene.panama.zstd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct ZSTD_bounds {
 *     unsigned long error;
 *     int lowerBound;
 *     int upperBound;
 * };
 * }
 */
public class ZSTD_bounds {

    public static MemoryLayout $LAYOUT() {
        return constants$5.const$0;
    }
    public static VarHandle error$VH() {
        return constants$5.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long error;
     * }
     */
    public static long error$get(MemorySegment seg) {
        return (long)constants$5.const$1.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long error;
     * }
     */
    public static void error$set(MemorySegment seg, long x) {
        constants$5.const$1.set(seg, 0L, x);
    }
    public static long error$get(MemorySegment seg, long index) {
        return (long)constants$5.const$1.get(seg, index * sizeof());    }
    public static void error$set(MemorySegment seg, long index, long x) {
        constants$5.const$1.set(seg, index * sizeof(), x);
    }
    public static VarHandle lowerBound$VH() {
        return constants$5.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int lowerBound;
     * }
     */
    public static int lowerBound$get(MemorySegment seg) {
        return (int)constants$5.const$2.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int lowerBound;
     * }
     */
    public static void lowerBound$set(MemorySegment seg, int x) {
        constants$5.const$2.set(seg, 0L, x);
    }
    public static int lowerBound$get(MemorySegment seg, long index) {
        return (int)constants$5.const$2.get(seg, index * sizeof());    }
    public static void lowerBound$set(MemorySegment seg, long index, int x) {
        constants$5.const$2.set(seg, index * sizeof(), x);
    }
    public static VarHandle upperBound$VH() {
        return constants$5.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int upperBound;
     * }
     */
    public static int upperBound$get(MemorySegment seg) {
        return (int)constants$5.const$3.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int upperBound;
     * }
     */
    public static void upperBound$set(MemorySegment seg, int x) {
        constants$5.const$3.set(seg, 0L, x);
    }
    public static int upperBound$get(MemorySegment seg, long index) {
        return (int)constants$5.const$3.get(seg, index * sizeof());    }
    public static void upperBound$set(MemorySegment seg, long index, int x) {
        constants$5.const$3.set(seg, index * sizeof(), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


